### ISSUE TITLE
Text Einheit Tags

### ISSUE THREAD

**Issue by PraktikantJulian** [BeWiBu/VE-Designer#13]
![text_einheiten_tags](https://cloud.githubusercontent.com/assets/27203651/24897693/338ca2a6-1e9a-11e7-9bed-2a0b8494cac7.png)
Das selbe Problem wie bei den Namen mit Tags.
Online zeigt der Text die Einheit nicht an

**Comment by BeWiBu** [comment]
Wer macht das mit Einheit ??? :)
