### ISSUE TITLE
Link online Nachfrage ob gespeichert wurde

### ISSUE THREAD

**Issue by PraktikantJulian** [BeWiBu/VE-Designer#28]
![beschriftung_verhalten](https://cloud.githubusercontent.com/assets/27203651/24994354/bfe38076-202a-11e7-80a8-7f61a3805e52.png)
Wenn man im Editor online auf einen Link klickt, der nicht ein neues Fenster öffnet, sollte wenn möglich nachgefragt werden ob man gespeichert hat.

**Comment by BeWiBu** [comment]
Komisch - nix geändert - jetzt gehts aber!?
