### ISSUE TITLE
Datentabelle, Balkendiagram, Kreisdiagramm, Linienschreiber nach online einen Error

### ISSUE THREAD

**Issue by PraktikantJulian** [BeWiBu/VE-Designer#29]
![datentabelle_error](https://cloud.githubusercontent.com/assets/27203651/24995970/41e5bfd4-2031-11e7-83d9-781e115b1e44.png)
Neu hinzugefügte **Datentabelle, Balkendiagram, Kreisdiagramm, Linienschreiber** verursacht ohne Werte nach online einen Error

**Comment by BeWiBu** [comment]
Sämtliche Fehlerausgaben beseitigt, aber die Eingänge machen in diesem Beispiel auch keinen Sinn, daher wird issue geschlossen
