### ISSUE TITLE
Logik Verbindung ziehen und währenddessen Scrollen

### ISSUE THREAD

**Issue by PraktikantJulian** [BeWiBu/VE-Designer#45]
![logik_scrolen](https://cloud.githubusercontent.com/assets/27203651/25176585/dc7953d6-24fe-11e7-88d2-d783094f415d.png)
Wenn man zwei Logik-Controlls hat und eins so weit nach unten verschiebt, dass es aus dem Bildschirm ist und eine Verbindung nach unten zieht und währenddessen scrollt geht die Verbindung nicht mit.

**Comment by BeWiBu** [comment]
Hat sich m.E. durch das neu-eingebaute Zooming erübrigt
